#+OPTIONS: toc:nil H:10

#+LaTeX_HEADER: \usepackage{mycv}

#+MACRO: first  Reuben
#+MACRO: last   Peter-Paul
#+MACRO: full {{{first}}} {{{last}}}
#+MACRO: email reuben.peterpaul@gmail.com
#+MACRO: phone  (506) 447-0612

#+TITLE: Reuben Peter-Paul

* Contact Information
** Email 
reuben.peterpaul@gmail.com
** Mobile
{{{phone}}}
** Homepage
[[http://re.vu/reubenpeterpaul][re.vu/reubenPeterPaul]]

* Work Experience
** May 2012 - /Present/
   *Senior Software Engineer*, [[http://ipsnp.wikidot.com/][IPSNP Computing Inc.]], Saint John, New Brunswick

   As a (part-time) Senior Software Engineer with IPSNP Computing Inc., I am involved
   in the development of semantic web technologies applied to bioinformatics and
   clinical intelligence. These activities have involved the design and development of
   an EBNF grammar, parsers, and an abstract syntax library for a proprietary SPARQL-
   like trace language.
   Additionally, I have been designing and developing a
   specialized rule generator used to validate and tune a proprietary reasoner called
   [[http://ipsnp.wikidot.com/hydra][Hydra]].

** March 2012 - /Present/
   *Information and Communications Technology Officer*, [[http://awdi-nb.com][Aboriginal Workforce Development Initiative]], Fredericton, New Brunswick

   As Information and Communications Technology (ICT) Officer, I am involved in the
   design, implementation and execution of a federally funded project directed at the
   development of the New Brunswick Aboriginal Information and Communications
   Technology ([[http://awdi-nb.org/ict.html][NBAICT]]) project. A specialized training program, identified to meet the
   growing demand for skilled workers in the ICT industry. To accomplish this we are
   actively pursuing partnerships with (Canadian) federal and provincial government
   representatives, First Nation leaders, ICT councils and Industry leaders. I also play a
   key role in the direction, design and development of the curricula to be used for the
   training concentrations.

** February 2009 - February 2012
   *Prototype Development Specialist*, [[http://www.nrc-cnrc.gc.ca][National Research Council]], Fredericton, New Brunswick

   /2011 Q1 - 2012 Q4/, I am part of a large effort involving several Research Officers, Application Specialists and industry parteners on the Dose Registry and Radiation Exposure Management (REM) systems.  I have played an active role as a technical lead and led implementation and execution of several key initiatives: continuous integration, systems design and architecture, build automation, database administration, system integration, application security, information auditing and software development.

   /2010 Q2 - 2011 Q1/, I was tasked as a technical lead to rearchitect the OmniBid an “open system for many-to-many automated negotiation”.  This work involved collaboration with an NRC Research Officer (Scott Buffet) industry partner (confidential).  Additionally, I incorporated continuous integration (CI) using Jenkins, Behaviour Driven Development (BDD) using Cucumber and dependency management using Apache Ivy.

   /2009 Q1 - 2010 Q2/, I collaborated with an NRC Research Officer (Bill McIver Jr) and an industry partner (Red Ball Internet) to develop an Automatic Vehicle Location (AVL) and fleet management information systems.  Several prototypes and ideas were proved, including: IP PBX-based Interactive Voice Response system using Asterisk / Adhearsion, Twitter-based push notification service, Automatic Voice Annunciation (AVA) system to announce upcoming major intersections or stops.  This collaboration was awarded a KIRA award for Technological Advancement and Innovation in the Private sector in 2010.

** May 2008 - February 2009
   *Software Consultant*, [[http://www.accreon.com][Accreon]], Fredericton, New Brunswick

   I was hired as a software consultant to participate in the development of a software product for an existing client.  I was involved in the redesign of several important business and information processes and then tasked to implement them.  I was also responsible for managing releases of the product.

** January 2006 - April 2008
   *Research Assistant*, [[http://www.cs.unb.ca][Faculty of Computer Science]], [[http://www.unb.ca][University of New Brunswick]], Fredericton, New Brunswick

   I was involved in the development of a new structural representational formalism, the Evolving Transformation System (ETS).  My activities as member of the ETS group included: development and formalization of new ETS concepts; collaborating on research papers for publication and conferences; and drafting technical drawings for data visualization, technical papers, posters and presentations.
   
   I also participated in a short prototyping project, with my co-supervisor Dr. Du, involving the development of custom software for the Sony Playstation Portable (PSP). 

** January 2006 - April 2008
   *Teaching Assistant*, [[http://www.cs.unb.ca][Faculty of Computer Science]], [[http://www.unb.ca][University of New Brunswick]], Fredericton, New Brunswick

   I assisted in class labs and I marked assignments for several introductory, intermediate and advanced subjects, e.g.: basic programming, Internet technologies, design patterns, and software architecture.
   
** May 2005 - December 2005
   *Software Developer*, Isomni Solutions Inc., Fredericton, New Brunswick

   I was involved in programming of an e-learning course management solution (iLearn).  I also designed and developed web-based user interface and a reference manual.

* Education
** December 2006 - May 2009
   *Master of Computer Science*, Specializing in data representation and visualization for pattern recognition and machine learning.
   (Thesis: [[http://www.cs.unb.ca/~goldfarb/Theses/Reuben.pdf][On the role of temporal and spatial representations in light of the ETS formalism]])

** Institution
   University of New Brunswick

** September 2000 - May 2005
   *Bachelor of Computer Science*, [[http://www.unb.ca/fredericton/cs/undergrad/bcs/index.html][Co-op]], Honours and designated Major in Software Systems
   (Honours thesis title: Why is the String an Unreliable Data Structure?)

** Institution
    University of New Brunswick

* Other Projects
** RuleML PSOA
    I am an active contributor to the [[http://ruleml.org/#PSOA][RuleML PSOA specification]] as part of the [[http://reubenpeterpaul.github.com/PSOA-to-TPTP/][PSOA2TPTP]] project.  (Also see [[Publications and Paper Presentations][Publication List]] below.)

* Selected Technical Skills and Abilities [fn:1]
** Programming Languages
    - General :: Java, Haskell, Lisp, Clojure, C/C++, Objective-C
    - Scripting :: JavaScript, PL/SQL, BASH
    - Markup :: HTML5, LaTeX, Markdown, Restructured Text, HAML
    - Learning :: Clojure, Erlang, Scala, Python, ML, ZSH
    - Build/Deployment Tools :: Maven, Ant, Automake, Rake, Capistrano, Leiningen
    
** Application Programming Interfaces (API) and Frameworks
    - APIs :: J2EE, JAX-RS, JPA, JMS, Java Servlet, OSGI, Java Agent Development Environment (JADE)
    - Frameworks :: jQuery, Ruby on Rails, Flex, Snap, Adhearsion, Jersey, RESTEasy, ANTLR, Parsec,
    - Automated Testing :: xUnit, Cucumber, Mockito, RSpec

**  Software Engineering
    - Architectural Styles :: REpresentational State Transfer (REST), MVC, Web Template Engines, Pipeline
    - Development Methodologies :: Agile, Extreme Programming (XP), Scrum, TDD/BDD/FDD 

** Programming Theory 
    - [[http://en.wikipedia.org/wiki/Programming_paradigm][Paradigms]] :: Object-Oriented (OOP), Function (FP), Metaprogramming
    - Theory :: (Typed/Untyped) Lambda Calculus, Pi Calculus

** Servers
    - Web :: Apache HTTP, Tomcat, Mongrel, Node.js, Jetty, Snap
    - Stack :: JBoss, JMX, Equinox, SpringSource dm Server, JADE
    - Database :: MySQL, Oracle, PostgreSQL, SQLite, MongoDB, BigTable
    - Version Control :: Git, Subversion
    - Repository :: Apache Ivy, Sonatype Nexus
    - Continuous Integration :: Jenkins

** Authoring
    - Code :: emacs, vim, eclipse, Xcode, Matlab
    - Text :: Org-mode, ScribTeX 
    - Interface :: Interface Builder
    - Diagrams :: UMLet, Visio
    
** Telephony
    - IVR :: Asterisk, Festival TTS

[fn:1] See my [[http://re.vu/reubenPeterPaul][Skill Proficiency Graph]].   

* Publications and Paper Presentations
  * Zou, G., Peter-Paul, R., Boley, H., Riazanov, A. “PSOA2TPTP: A Reference Translator for Interoperating PSOA RuleML with TPTP Reasoners”. In: Bikakis, A., Giurca, A. (eds.) RuleML 2012. LNCS, vol. 7438, pp. 264–279. Springer, Heidelberg (2012)
  * Gen Zou, Reuben Peter-Paul, Harold Boley and Alexandre Riazanov, “PSOA2TPTP: Designing and Prototyping a Translator from PSOA RuleML to TPTP Format”, poster presented at UNB Computer Science Research Expo, April 4, 2012
  * L. Goldfarb, I. Scrimger, B. R. Peter-Paul, “ETS as a structural language for decision modeling and analysis: Planning, anticipation and monitoring ”, Risk and Decision Analysis Journal, Vol. 1 Number 2, 2009 
  * L. Goldfarb, B. R. Peter-Paul, I. Scrimger, “ETS Representation of Human Movement”, poster presented at UNB Computer Science Research Expo, April 4, 2007 
  * B. R. Peter-Paul, “Why is the String an Unreliable Data Structure?”, presented my undergraduate honors thesis at APICS 29th Annual Conference, Acadia University, October 21-23, 2005

* Awards and Recognition
** May 2010
   *KIRA, Technological Advancement and Innovation in the Private Sector*, our team was recognized for our automatic vehicle location platform developed in partnership with [[http://redballinternet.com][Red Ball Internet]].

** August 2008
   *Post Secondary Education Achievement*, I was recognized by the Pabineau First Nation community for successfully obtaining a master's degree in Computer Science.

* References
/Available upon request./
